AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SerbetBlockchain
  
Globals:
  Function:
    Timeout: 3
Resources:
  SerbetBlockchain:
    Type: AWS::Serverless::Function
    Properties:
<<<<<<< HEAD
      CodeUri: src/
=======
      CodeUri: serbet-blockchain/
>>>>>>> 17c97f86b8a19987fe766e4c22b8628f399847b8
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 1024
      Timeout: 500
      Architectures:
        - x86_64
